# Autogenerated using ProtoBuf.jl v1.2.0 on 2025-10-28T18:17:46.491
# original file: /home/jrklasen/dev/moviro/GTFSRealtimes.jl/generate/proto/gtfs-realtime.proto (proto2 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export var"VehicleDescriptor.WheelchairAccessible", Position, ReplacementStop
export var"Alert.Cause", Shape, var"VehiclePosition.OccupancyStatus"
export var"FeedHeader.Incrementality", TimeRange, var"TranslatedString.Translation"
export var"TripUpdate.TripProperties", var"VehiclePosition.VehicleStopStatus"
export var"TripDescriptor.ScheduleRelationship", var"Stop.WheelchairBoarding"
export var"VehiclePosition.CongestionLevel"
export var"TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType"
export var"Alert.SeverityLevel", var"Alert.Effect", var"TranslatedImage.LocalizedImage"
export var"TripModifications.SelectedTrips", StopSelector
export var"TripDescriptor.ModifiedTripSelector", var"TripUpdate.StopTimeEvent"
export var"TripUpdate.StopTimeUpdate.ScheduleRelationship", VehicleDescriptor
export var"VehiclePosition.CarriageDetails", FeedHeader, TranslatedString
export var"TripUpdate.StopTimeUpdate.StopTimeProperties", TranslatedImage
export var"TripModifications.Modification", TripDescriptor, Stop
export var"TripUpdate.StopTimeUpdate", TripModifications, EntitySelector, VehiclePosition
export TripUpdate, Alert, FeedEntity, FeedMessage


@enumx var"VehicleDescriptor.WheelchairAccessible" NO_VALUE = 0 UNKNOWN = 1 WHEELCHAIR_ACCESSIBLE = 2 WHEELCHAIR_INACCESSIBLE = 3

struct Position
    latitude::Float32
    longitude::Float32
    bearing::Float32
    odometer::Float64
    speed::Float32
end
PB.extendable_field_numbers(::Type{Position}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{Position}) = (; latitude = zero(Float32), longitude = zero(Float32), bearing = zero(Float32), odometer = zero(Float64), speed = zero(Float32))
PB.field_numbers(::Type{Position}) = (; latitude = 1, longitude = 2, bearing = 3, odometer = 4, speed = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Position})
    latitude = zero(Float32)
    longitude = zero(Float32)
    bearing = zero(Float32)
    odometer = zero(Float64)
    speed = zero(Float32)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            latitude = PB.decode(d, Float32)
        elseif field_number == 2
            longitude = PB.decode(d, Float32)
        elseif field_number == 3
            bearing = PB.decode(d, Float32)
        elseif field_number == 4
            odometer = PB.decode(d, Float64)
        elseif field_number == 5
            speed = PB.decode(d, Float32)
        else
            Base.skip(d, wire_type)
        end
    end
    return Position(latitude, longitude, bearing, odometer, speed)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Position)
    initpos = position(e.io)
    PB.encode(e, 1, x.latitude)
    PB.encode(e, 2, x.longitude)
    x.bearing !== zero(Float32) && PB.encode(e, 3, x.bearing)
    x.odometer !== zero(Float64) && PB.encode(e, 4, x.odometer)
    x.speed !== zero(Float32) && PB.encode(e, 5, x.speed)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Position)
    encoded_size = 0
    encoded_size += PB._encoded_size(x.latitude, 1)
    encoded_size += PB._encoded_size(x.longitude, 2)
    x.bearing !== zero(Float32) && (encoded_size += PB._encoded_size(x.bearing, 3))
    x.odometer !== zero(Float64) && (encoded_size += PB._encoded_size(x.odometer, 4))
    x.speed !== zero(Float32) && (encoded_size += PB._encoded_size(x.speed, 5))
    return encoded_size
end

struct ReplacementStop
    travel_time_to_stop::Int32
    stop_id::String
end
PB.extendable_field_numbers(::Type{ReplacementStop}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{ReplacementStop}) = (; travel_time_to_stop = zero(Int32), stop_id = "")
PB.field_numbers(::Type{ReplacementStop}) = (; travel_time_to_stop = 1, stop_id = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ReplacementStop})
    travel_time_to_stop = zero(Int32)
    stop_id = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            travel_time_to_stop = PB.decode(d, Int32)
        elseif field_number == 2
            stop_id = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return ReplacementStop(travel_time_to_stop, stop_id)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ReplacementStop)
    initpos = position(e.io)
    x.travel_time_to_stop != zero(Int32) && PB.encode(e, 1, x.travel_time_to_stop)
    !isempty(x.stop_id) && PB.encode(e, 2, x.stop_id)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ReplacementStop)
    encoded_size = 0
    x.travel_time_to_stop != zero(Int32) && (encoded_size += PB._encoded_size(x.travel_time_to_stop, 1))
    !isempty(x.stop_id) && (encoded_size += PB._encoded_size(x.stop_id, 2))
    return encoded_size
end

@enumx var"Alert.Cause" UNKNOWN_CAUSE = 1 OTHER_CAUSE = 2 TECHNICAL_PROBLEM = 3 STRIKE = 4 DEMONSTRATION = 5 ACCIDENT = 6 HOLIDAY = 7 WEATHER = 8 MAINTENANCE = 9 CONSTRUCTION = 10 POLICE_ACTIVITY = 11 MEDICAL_EMERGENCY = 12

struct Shape
    shape_id::String
    encoded_polyline::String
end
PB.extendable_field_numbers(::Type{Shape}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{Shape}) = (; shape_id = "", encoded_polyline = "")
PB.field_numbers(::Type{Shape}) = (; shape_id = 1, encoded_polyline = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Shape})
    shape_id = ""
    encoded_polyline = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            shape_id = PB.decode(d, String)
        elseif field_number == 2
            encoded_polyline = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return Shape(shape_id, encoded_polyline)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Shape)
    initpos = position(e.io)
    !isempty(x.shape_id) && PB.encode(e, 1, x.shape_id)
    !isempty(x.encoded_polyline) && PB.encode(e, 2, x.encoded_polyline)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Shape)
    encoded_size = 0
    !isempty(x.shape_id) && (encoded_size += PB._encoded_size(x.shape_id, 1))
    !isempty(x.encoded_polyline) && (encoded_size += PB._encoded_size(x.encoded_polyline, 2))
    return encoded_size
end

@enumx var"VehiclePosition.OccupancyStatus" EMPTY = 0 MANY_SEATS_AVAILABLE = 1 FEW_SEATS_AVAILABLE = 2 STANDING_ROOM_ONLY = 3 CRUSHED_STANDING_ROOM_ONLY = 4 FULL = 5 NOT_ACCEPTING_PASSENGERS = 6 NO_DATA_AVAILABLE = 7 NOT_BOARDABLE = 8

@enumx var"FeedHeader.Incrementality" FULL_DATASET = 0 DIFFERENTIAL = 1

struct TimeRange
    start::UInt64
    var"#end"::UInt64
end
PB.extendable_field_numbers(::Type{TimeRange}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{TimeRange}) = (; start = zero(UInt64), var"#end" = zero(UInt64))
PB.field_numbers(::Type{TimeRange}) = (; start = 1, var"#end" = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TimeRange})
    start = zero(UInt64)
    var"#end" = zero(UInt64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            start = PB.decode(d, UInt64)
        elseif field_number == 2
            var"#end" = PB.decode(d, UInt64)
        else
            Base.skip(d, wire_type)
        end
    end
    return TimeRange(start, var"#end")
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TimeRange)
    initpos = position(e.io)
    x.start != zero(UInt64) && PB.encode(e, 1, x.start)
    x.var"#end" != zero(UInt64) && PB.encode(e, 2, x.var"#end")
    return position(e.io) - initpos
end
function PB._encoded_size(x::TimeRange)
    encoded_size = 0
    x.start != zero(UInt64) && (encoded_size += PB._encoded_size(x.start, 1))
    x.var"#end" != zero(UInt64) && (encoded_size += PB._encoded_size(x.var"#end", 2))
    return encoded_size
end

struct var"TranslatedString.Translation"
    text::String
    language::String
end
PB.extendable_field_numbers(::Type{var"TranslatedString.Translation"}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{var"TranslatedString.Translation"}) = (; text = "", language = "")
PB.field_numbers(::Type{var"TranslatedString.Translation"}) = (; text = 1, language = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"TranslatedString.Translation"})
    text = ""
    language = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            text = PB.decode(d, String)
        elseif field_number == 2
            language = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"TranslatedString.Translation"(text, language)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"TranslatedString.Translation")
    initpos = position(e.io)
    PB.encode(e, 1, x.text)
    !isempty(x.language) && PB.encode(e, 2, x.language)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"TranslatedString.Translation")
    encoded_size = 0
    encoded_size += PB._encoded_size(x.text, 1)
    !isempty(x.language) && (encoded_size += PB._encoded_size(x.language, 2))
    return encoded_size
end

struct var"TripUpdate.TripProperties"
    trip_id::String
    start_date::String
    start_time::String
    shape_id::String
    trip_headsign::String
    trip_short_name::String
end
PB.extendable_field_numbers(::Type{var"TripUpdate.TripProperties"}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{var"TripUpdate.TripProperties"}) = (; trip_id = "", start_date = "", start_time = "", shape_id = "", trip_headsign = "", trip_short_name = "")
PB.field_numbers(::Type{var"TripUpdate.TripProperties"}) = (; trip_id = 1, start_date = 2, start_time = 3, shape_id = 4, trip_headsign = 5, trip_short_name = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"TripUpdate.TripProperties"})
    trip_id = ""
    start_date = ""
    start_time = ""
    shape_id = ""
    trip_headsign = ""
    trip_short_name = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            trip_id = PB.decode(d, String)
        elseif field_number == 2
            start_date = PB.decode(d, String)
        elseif field_number == 3
            start_time = PB.decode(d, String)
        elseif field_number == 4
            shape_id = PB.decode(d, String)
        elseif field_number == 5
            trip_headsign = PB.decode(d, String)
        elseif field_number == 6
            trip_short_name = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"TripUpdate.TripProperties"(trip_id, start_date, start_time, shape_id, trip_headsign, trip_short_name)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"TripUpdate.TripProperties")
    initpos = position(e.io)
    !isempty(x.trip_id) && PB.encode(e, 1, x.trip_id)
    !isempty(x.start_date) && PB.encode(e, 2, x.start_date)
    !isempty(x.start_time) && PB.encode(e, 3, x.start_time)
    !isempty(x.shape_id) && PB.encode(e, 4, x.shape_id)
    !isempty(x.trip_headsign) && PB.encode(e, 5, x.trip_headsign)
    !isempty(x.trip_short_name) && PB.encode(e, 6, x.trip_short_name)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"TripUpdate.TripProperties")
    encoded_size = 0
    !isempty(x.trip_id) && (encoded_size += PB._encoded_size(x.trip_id, 1))
    !isempty(x.start_date) && (encoded_size += PB._encoded_size(x.start_date, 2))
    !isempty(x.start_time) && (encoded_size += PB._encoded_size(x.start_time, 3))
    !isempty(x.shape_id) && (encoded_size += PB._encoded_size(x.shape_id, 4))
    !isempty(x.trip_headsign) && (encoded_size += PB._encoded_size(x.trip_headsign, 5))
    !isempty(x.trip_short_name) && (encoded_size += PB._encoded_size(x.trip_short_name, 6))
    return encoded_size
end

@enumx var"VehiclePosition.VehicleStopStatus" INCOMING_AT = 0 STOPPED_AT = 1 IN_TRANSIT_TO = 2

@enumx var"TripDescriptor.ScheduleRelationship" SCHEDULED = 0 ADDED = 1 UNSCHEDULED = 2 CANCELED = 3 REPLACEMENT = 5 DUPLICATED = 6 DELETED = 7 NEW = 8

@enumx var"Stop.WheelchairBoarding" UNKNOWN = 0 AVAILABLE = 1 NOT_AVAILABLE = 2

@enumx var"VehiclePosition.CongestionLevel" UNKNOWN_CONGESTION_LEVEL = 0 RUNNING_SMOOTHLY = 1 STOP_AND_GO = 2 CONGESTION = 3 SEVERE_CONGESTION = 4

@enumx var"TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType" REGULAR = 0 NONE = 1 PHONE_AGENCY = 2 COORDINATE_WITH_DRIVER = 3

@enumx var"Alert.SeverityLevel" UNKNOWN_SEVERITY = 1 INFO = 2 WARNING = 3 SEVERE = 4

@enumx var"Alert.Effect" NO_SERVICE = 1 REDUCED_SERVICE = 2 SIGNIFICANT_DELAYS = 3 DETOUR = 4 ADDITIONAL_SERVICE = 5 MODIFIED_SERVICE = 6 OTHER_EFFECT = 7 UNKNOWN_EFFECT = 8 STOP_MOVED = 9 NO_EFFECT = 10 ACCESSIBILITY_ISSUE = 11

struct var"TranslatedImage.LocalizedImage"
    url::String
    media_type::String
    language::String
end
PB.extendable_field_numbers(::Type{var"TranslatedImage.LocalizedImage"}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{var"TranslatedImage.LocalizedImage"}) = (; url = "", media_type = "", language = "")
PB.field_numbers(::Type{var"TranslatedImage.LocalizedImage"}) = (; url = 1, media_type = 2, language = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"TranslatedImage.LocalizedImage"})
    url = ""
    media_type = ""
    language = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            url = PB.decode(d, String)
        elseif field_number == 2
            media_type = PB.decode(d, String)
        elseif field_number == 3
            language = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"TranslatedImage.LocalizedImage"(url, media_type, language)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"TranslatedImage.LocalizedImage")
    initpos = position(e.io)
    PB.encode(e, 1, x.url)
    PB.encode(e, 2, x.media_type)
    !isempty(x.language) && PB.encode(e, 3, x.language)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"TranslatedImage.LocalizedImage")
    encoded_size = 0
    encoded_size += PB._encoded_size(x.url, 1)
    encoded_size += PB._encoded_size(x.media_type, 2)
    !isempty(x.language) && (encoded_size += PB._encoded_size(x.language, 3))
    return encoded_size
end

struct var"TripModifications.SelectedTrips"
    trip_ids::Vector{String}
    shape_id::String
end
PB.extendable_field_numbers(::Type{var"TripModifications.SelectedTrips"}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{var"TripModifications.SelectedTrips"}) = (; trip_ids = Vector{String}(), shape_id = "")
PB.field_numbers(::Type{var"TripModifications.SelectedTrips"}) = (; trip_ids = 1, shape_id = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"TripModifications.SelectedTrips"})
    trip_ids = PB.BufferedVector{String}()
    shape_id = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, trip_ids)
        elseif field_number == 2
            shape_id = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"TripModifications.SelectedTrips"(trip_ids[], shape_id)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"TripModifications.SelectedTrips")
    initpos = position(e.io)
    !isempty(x.trip_ids) && PB.encode(e, 1, x.trip_ids)
    !isempty(x.shape_id) && PB.encode(e, 2, x.shape_id)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"TripModifications.SelectedTrips")
    encoded_size = 0
    !isempty(x.trip_ids) && (encoded_size += PB._encoded_size(x.trip_ids, 1))
    !isempty(x.shape_id) && (encoded_size += PB._encoded_size(x.shape_id, 2))
    return encoded_size
end

struct StopSelector
    stop_sequence::UInt32
    stop_id::String
end
PB.extendable_field_numbers(::Type{StopSelector}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{StopSelector}) = (; stop_sequence = zero(UInt32), stop_id = "")
PB.field_numbers(::Type{StopSelector}) = (; stop_sequence = 1, stop_id = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:StopSelector})
    stop_sequence = zero(UInt32)
    stop_id = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            stop_sequence = PB.decode(d, UInt32)
        elseif field_number == 2
            stop_id = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return StopSelector(stop_sequence, stop_id)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::StopSelector)
    initpos = position(e.io)
    x.stop_sequence != zero(UInt32) && PB.encode(e, 1, x.stop_sequence)
    !isempty(x.stop_id) && PB.encode(e, 2, x.stop_id)
    return position(e.io) - initpos
end
function PB._encoded_size(x::StopSelector)
    encoded_size = 0
    x.stop_sequence != zero(UInt32) && (encoded_size += PB._encoded_size(x.stop_sequence, 1))
    !isempty(x.stop_id) && (encoded_size += PB._encoded_size(x.stop_id, 2))
    return encoded_size
end

struct var"TripDescriptor.ModifiedTripSelector"
    modifications_id::String
    affected_trip_id::String
    start_time::String
    start_date::String
end
PB.extendable_field_numbers(::Type{var"TripDescriptor.ModifiedTripSelector"}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{var"TripDescriptor.ModifiedTripSelector"}) = (; modifications_id = "", affected_trip_id = "", start_time = "", start_date = "")
PB.field_numbers(::Type{var"TripDescriptor.ModifiedTripSelector"}) = (; modifications_id = 1, affected_trip_id = 2, start_time = 3, start_date = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"TripDescriptor.ModifiedTripSelector"})
    modifications_id = ""
    affected_trip_id = ""
    start_time = ""
    start_date = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            modifications_id = PB.decode(d, String)
        elseif field_number == 2
            affected_trip_id = PB.decode(d, String)
        elseif field_number == 3
            start_time = PB.decode(d, String)
        elseif field_number == 4
            start_date = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"TripDescriptor.ModifiedTripSelector"(modifications_id, affected_trip_id, start_time, start_date)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"TripDescriptor.ModifiedTripSelector")
    initpos = position(e.io)
    !isempty(x.modifications_id) && PB.encode(e, 1, x.modifications_id)
    !isempty(x.affected_trip_id) && PB.encode(e, 2, x.affected_trip_id)
    !isempty(x.start_time) && PB.encode(e, 3, x.start_time)
    !isempty(x.start_date) && PB.encode(e, 4, x.start_date)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"TripDescriptor.ModifiedTripSelector")
    encoded_size = 0
    !isempty(x.modifications_id) && (encoded_size += PB._encoded_size(x.modifications_id, 1))
    !isempty(x.affected_trip_id) && (encoded_size += PB._encoded_size(x.affected_trip_id, 2))
    !isempty(x.start_time) && (encoded_size += PB._encoded_size(x.start_time, 3))
    !isempty(x.start_date) && (encoded_size += PB._encoded_size(x.start_date, 4))
    return encoded_size
end

struct var"TripUpdate.StopTimeEvent"
    delay::Int32
    time::Int64
    uncertainty::Int32
    scheduled_time::Int64
end
PB.extendable_field_numbers(::Type{var"TripUpdate.StopTimeEvent"}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{var"TripUpdate.StopTimeEvent"}) = (; delay = zero(Int32), time = zero(Int64), uncertainty = zero(Int32), scheduled_time = zero(Int64))
PB.field_numbers(::Type{var"TripUpdate.StopTimeEvent"}) = (; delay = 1, time = 2, uncertainty = 3, scheduled_time = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"TripUpdate.StopTimeEvent"})
    delay = zero(Int32)
    time = zero(Int64)
    uncertainty = zero(Int32)
    scheduled_time = zero(Int64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            delay = PB.decode(d, Int32)
        elseif field_number == 2
            time = PB.decode(d, Int64)
        elseif field_number == 3
            uncertainty = PB.decode(d, Int32)
        elseif field_number == 4
            scheduled_time = PB.decode(d, Int64)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"TripUpdate.StopTimeEvent"(delay, time, uncertainty, scheduled_time)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"TripUpdate.StopTimeEvent")
    initpos = position(e.io)
    x.delay != zero(Int32) && PB.encode(e, 1, x.delay)
    x.time != zero(Int64) && PB.encode(e, 2, x.time)
    x.uncertainty != zero(Int32) && PB.encode(e, 3, x.uncertainty)
    x.scheduled_time != zero(Int64) && PB.encode(e, 4, x.scheduled_time)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"TripUpdate.StopTimeEvent")
    encoded_size = 0
    x.delay != zero(Int32) && (encoded_size += PB._encoded_size(x.delay, 1))
    x.time != zero(Int64) && (encoded_size += PB._encoded_size(x.time, 2))
    x.uncertainty != zero(Int32) && (encoded_size += PB._encoded_size(x.uncertainty, 3))
    x.scheduled_time != zero(Int64) && (encoded_size += PB._encoded_size(x.scheduled_time, 4))
    return encoded_size
end

@enumx var"TripUpdate.StopTimeUpdate.ScheduleRelationship" SCHEDULED = 0 SKIPPED = 1 NO_DATA = 2 UNSCHEDULED = 3

struct VehicleDescriptor
    id::String
    label::String
    license_plate::String
    wheelchair_accessible::var"VehicleDescriptor.WheelchairAccessible".T
end
PB.extendable_field_numbers(::Type{VehicleDescriptor}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{VehicleDescriptor}) = (; id = "", label = "", license_plate = "", wheelchair_accessible = var"VehicleDescriptor.WheelchairAccessible".NO_VALUE)
PB.field_numbers(::Type{VehicleDescriptor}) = (; id = 1, label = 2, license_plate = 3, wheelchair_accessible = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:VehicleDescriptor})
    id = ""
    label = ""
    license_plate = ""
    wheelchair_accessible = var"VehicleDescriptor.WheelchairAccessible".NO_VALUE
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            id = PB.decode(d, String)
        elseif field_number == 2
            label = PB.decode(d, String)
        elseif field_number == 3
            license_plate = PB.decode(d, String)
        elseif field_number == 4
            wheelchair_accessible = PB.decode(d, var"VehicleDescriptor.WheelchairAccessible".T)
        else
            Base.skip(d, wire_type)
        end
    end
    return VehicleDescriptor(id, label, license_plate, wheelchair_accessible)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::VehicleDescriptor)
    initpos = position(e.io)
    !isempty(x.id) && PB.encode(e, 1, x.id)
    !isempty(x.label) && PB.encode(e, 2, x.label)
    !isempty(x.license_plate) && PB.encode(e, 3, x.license_plate)
    x.wheelchair_accessible != var"VehicleDescriptor.WheelchairAccessible".NO_VALUE && PB.encode(e, 4, x.wheelchair_accessible)
    return position(e.io) - initpos
end
function PB._encoded_size(x::VehicleDescriptor)
    encoded_size = 0
    !isempty(x.id) && (encoded_size += PB._encoded_size(x.id, 1))
    !isempty(x.label) && (encoded_size += PB._encoded_size(x.label, 2))
    !isempty(x.license_plate) && (encoded_size += PB._encoded_size(x.license_plate, 3))
    x.wheelchair_accessible != var"VehicleDescriptor.WheelchairAccessible".NO_VALUE && (encoded_size += PB._encoded_size(x.wheelchair_accessible, 4))
    return encoded_size
end

struct var"VehiclePosition.CarriageDetails"
    id::String
    label::String
    occupancy_status::var"VehiclePosition.OccupancyStatus".T
    occupancy_percentage::Int32
    carriage_sequence::UInt32
end
PB.extendable_field_numbers(::Type{var"VehiclePosition.CarriageDetails"}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{var"VehiclePosition.CarriageDetails"}) = (; id = "", label = "", occupancy_status = var"VehiclePosition.OccupancyStatus".NO_DATA_AVAILABLE, occupancy_percentage = Int32(-1), carriage_sequence = zero(UInt32))
PB.field_numbers(::Type{var"VehiclePosition.CarriageDetails"}) = (; id = 1, label = 2, occupancy_status = 3, occupancy_percentage = 4, carriage_sequence = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"VehiclePosition.CarriageDetails"})
    id = ""
    label = ""
    occupancy_status = var"VehiclePosition.OccupancyStatus".NO_DATA_AVAILABLE
    occupancy_percentage = Int32(-1)
    carriage_sequence = zero(UInt32)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            id = PB.decode(d, String)
        elseif field_number == 2
            label = PB.decode(d, String)
        elseif field_number == 3
            occupancy_status = PB.decode(d, var"VehiclePosition.OccupancyStatus".T)
        elseif field_number == 4
            occupancy_percentage = PB.decode(d, Int32)
        elseif field_number == 5
            carriage_sequence = PB.decode(d, UInt32)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"VehiclePosition.CarriageDetails"(id, label, occupancy_status, occupancy_percentage, carriage_sequence)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"VehiclePosition.CarriageDetails")
    initpos = position(e.io)
    !isempty(x.id) && PB.encode(e, 1, x.id)
    !isempty(x.label) && PB.encode(e, 2, x.label)
    x.occupancy_status != var"VehiclePosition.OccupancyStatus".NO_DATA_AVAILABLE && PB.encode(e, 3, x.occupancy_status)
    x.occupancy_percentage != Int32(-1) && PB.encode(e, 4, x.occupancy_percentage)
    x.carriage_sequence != zero(UInt32) && PB.encode(e, 5, x.carriage_sequence)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"VehiclePosition.CarriageDetails")
    encoded_size = 0
    !isempty(x.id) && (encoded_size += PB._encoded_size(x.id, 1))
    !isempty(x.label) && (encoded_size += PB._encoded_size(x.label, 2))
    x.occupancy_status != var"VehiclePosition.OccupancyStatus".NO_DATA_AVAILABLE && (encoded_size += PB._encoded_size(x.occupancy_status, 3))
    x.occupancy_percentage != Int32(-1) && (encoded_size += PB._encoded_size(x.occupancy_percentage, 4))
    x.carriage_sequence != zero(UInt32) && (encoded_size += PB._encoded_size(x.carriage_sequence, 5))
    return encoded_size
end

struct FeedHeader
    gtfs_realtime_version::String
    incrementality::var"FeedHeader.Incrementality".T
    timestamp::UInt64
    feed_version::String
end
PB.extendable_field_numbers(::Type{FeedHeader}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{FeedHeader}) = (; gtfs_realtime_version = "", incrementality = var"FeedHeader.Incrementality".FULL_DATASET, timestamp = zero(UInt64), feed_version = "")
PB.field_numbers(::Type{FeedHeader}) = (; gtfs_realtime_version = 1, incrementality = 2, timestamp = 3, feed_version = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:FeedHeader})
    gtfs_realtime_version = ""
    incrementality = var"FeedHeader.Incrementality".FULL_DATASET
    timestamp = zero(UInt64)
    feed_version = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            gtfs_realtime_version = PB.decode(d, String)
        elseif field_number == 2
            incrementality = PB.decode(d, var"FeedHeader.Incrementality".T)
        elseif field_number == 3
            timestamp = PB.decode(d, UInt64)
        elseif field_number == 4
            feed_version = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return FeedHeader(gtfs_realtime_version, incrementality, timestamp, feed_version)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::FeedHeader)
    initpos = position(e.io)
    PB.encode(e, 1, x.gtfs_realtime_version)
    x.incrementality != var"FeedHeader.Incrementality".FULL_DATASET && PB.encode(e, 2, x.incrementality)
    x.timestamp != zero(UInt64) && PB.encode(e, 3, x.timestamp)
    !isempty(x.feed_version) && PB.encode(e, 4, x.feed_version)
    return position(e.io) - initpos
end
function PB._encoded_size(x::FeedHeader)
    encoded_size = 0
    encoded_size += PB._encoded_size(x.gtfs_realtime_version, 1)
    x.incrementality != var"FeedHeader.Incrementality".FULL_DATASET && (encoded_size += PB._encoded_size(x.incrementality, 2))
    x.timestamp != zero(UInt64) && (encoded_size += PB._encoded_size(x.timestamp, 3))
    !isempty(x.feed_version) && (encoded_size += PB._encoded_size(x.feed_version, 4))
    return encoded_size
end

struct TranslatedString
    translation::Vector{var"TranslatedString.Translation"}
end
PB.extendable_field_numbers(::Type{TranslatedString}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{TranslatedString}) = (; translation = Vector{var"TranslatedString.Translation"}())
PB.field_numbers(::Type{TranslatedString}) = (; translation = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TranslatedString})
    translation = PB.BufferedVector{var"TranslatedString.Translation"}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, translation)
        else
            Base.skip(d, wire_type)
        end
    end
    return TranslatedString(translation[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TranslatedString)
    initpos = position(e.io)
    !isempty(x.translation) && PB.encode(e, 1, x.translation)
    return position(e.io) - initpos
end
function PB._encoded_size(x::TranslatedString)
    encoded_size = 0
    !isempty(x.translation) && (encoded_size += PB._encoded_size(x.translation, 1))
    return encoded_size
end

struct var"TripUpdate.StopTimeUpdate.StopTimeProperties"
    assigned_stop_id::String
    stop_headsign::String
    pickup_type::var"TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType".T
    drop_off_type::var"TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType".T
end
PB.extendable_field_numbers(::Type{var"TripUpdate.StopTimeUpdate.StopTimeProperties"}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{var"TripUpdate.StopTimeUpdate.StopTimeProperties"}) = (; assigned_stop_id = "", stop_headsign = "", pickup_type = var"TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType".REGULAR, drop_off_type = var"TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType".REGULAR)
PB.field_numbers(::Type{var"TripUpdate.StopTimeUpdate.StopTimeProperties"}) = (; assigned_stop_id = 1, stop_headsign = 2, pickup_type = 3, drop_off_type = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"TripUpdate.StopTimeUpdate.StopTimeProperties"})
    assigned_stop_id = ""
    stop_headsign = ""
    pickup_type = var"TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType".REGULAR
    drop_off_type = var"TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType".REGULAR
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            assigned_stop_id = PB.decode(d, String)
        elseif field_number == 2
            stop_headsign = PB.decode(d, String)
        elseif field_number == 3
            pickup_type = PB.decode(d, var"TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType".T)
        elseif field_number == 4
            drop_off_type = PB.decode(d, var"TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType".T)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"TripUpdate.StopTimeUpdate.StopTimeProperties"(assigned_stop_id, stop_headsign, pickup_type, drop_off_type)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"TripUpdate.StopTimeUpdate.StopTimeProperties")
    initpos = position(e.io)
    !isempty(x.assigned_stop_id) && PB.encode(e, 1, x.assigned_stop_id)
    !isempty(x.stop_headsign) && PB.encode(e, 2, x.stop_headsign)
    x.pickup_type != var"TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType".REGULAR && PB.encode(e, 3, x.pickup_type)
    x.drop_off_type != var"TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType".REGULAR && PB.encode(e, 4, x.drop_off_type)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"TripUpdate.StopTimeUpdate.StopTimeProperties")
    encoded_size = 0
    !isempty(x.assigned_stop_id) && (encoded_size += PB._encoded_size(x.assigned_stop_id, 1))
    !isempty(x.stop_headsign) && (encoded_size += PB._encoded_size(x.stop_headsign, 2))
    x.pickup_type != var"TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType".REGULAR && (encoded_size += PB._encoded_size(x.pickup_type, 3))
    x.drop_off_type != var"TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType".REGULAR && (encoded_size += PB._encoded_size(x.drop_off_type, 4))
    return encoded_size
end

struct TranslatedImage
    localized_image::Vector{var"TranslatedImage.LocalizedImage"}
end
PB.extendable_field_numbers(::Type{TranslatedImage}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{TranslatedImage}) = (; localized_image = Vector{var"TranslatedImage.LocalizedImage"}())
PB.field_numbers(::Type{TranslatedImage}) = (; localized_image = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TranslatedImage})
    localized_image = PB.BufferedVector{var"TranslatedImage.LocalizedImage"}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, localized_image)
        else
            Base.skip(d, wire_type)
        end
    end
    return TranslatedImage(localized_image[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TranslatedImage)
    initpos = position(e.io)
    !isempty(x.localized_image) && PB.encode(e, 1, x.localized_image)
    return position(e.io) - initpos
end
function PB._encoded_size(x::TranslatedImage)
    encoded_size = 0
    !isempty(x.localized_image) && (encoded_size += PB._encoded_size(x.localized_image, 1))
    return encoded_size
end

struct var"TripModifications.Modification"
    start_stop_selector::Union{Nothing, StopSelector}
    end_stop_selector::Union{Nothing, StopSelector}
    propagated_modification_delay::Int32
    replacement_stops::Vector{ReplacementStop}
    service_alert_id::String
    last_modified_time::UInt64
end
PB.extendable_field_numbers(::Type{var"TripModifications.Modification"}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{var"TripModifications.Modification"}) = (; start_stop_selector = nothing, end_stop_selector = nothing, propagated_modification_delay = Int32(0), replacement_stops = Vector{ReplacementStop}(), service_alert_id = "", last_modified_time = zero(UInt64))
PB.field_numbers(::Type{var"TripModifications.Modification"}) = (; start_stop_selector = 1, end_stop_selector = 2, propagated_modification_delay = 3, replacement_stops = 4, service_alert_id = 5, last_modified_time = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"TripModifications.Modification"})
    start_stop_selector = Ref{Union{Nothing, StopSelector}}(nothing)
    end_stop_selector = Ref{Union{Nothing, StopSelector}}(nothing)
    propagated_modification_delay = Int32(0)
    replacement_stops = PB.BufferedVector{ReplacementStop}()
    service_alert_id = ""
    last_modified_time = zero(UInt64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, start_stop_selector)
        elseif field_number == 2
            PB.decode!(d, end_stop_selector)
        elseif field_number == 3
            propagated_modification_delay = PB.decode(d, Int32)
        elseif field_number == 4
            PB.decode!(d, replacement_stops)
        elseif field_number == 5
            service_alert_id = PB.decode(d, String)
        elseif field_number == 6
            last_modified_time = PB.decode(d, UInt64)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"TripModifications.Modification"(start_stop_selector[], end_stop_selector[], propagated_modification_delay, replacement_stops[], service_alert_id, last_modified_time)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"TripModifications.Modification")
    initpos = position(e.io)
    !isnothing(x.start_stop_selector) && PB.encode(e, 1, x.start_stop_selector)
    !isnothing(x.end_stop_selector) && PB.encode(e, 2, x.end_stop_selector)
    x.propagated_modification_delay != Int32(0) && PB.encode(e, 3, x.propagated_modification_delay)
    !isempty(x.replacement_stops) && PB.encode(e, 4, x.replacement_stops)
    !isempty(x.service_alert_id) && PB.encode(e, 5, x.service_alert_id)
    x.last_modified_time != zero(UInt64) && PB.encode(e, 6, x.last_modified_time)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"TripModifications.Modification")
    encoded_size = 0
    !isnothing(x.start_stop_selector) && (encoded_size += PB._encoded_size(x.start_stop_selector, 1))
    !isnothing(x.end_stop_selector) && (encoded_size += PB._encoded_size(x.end_stop_selector, 2))
    x.propagated_modification_delay != Int32(0) && (encoded_size += PB._encoded_size(x.propagated_modification_delay, 3))
    !isempty(x.replacement_stops) && (encoded_size += PB._encoded_size(x.replacement_stops, 4))
    !isempty(x.service_alert_id) && (encoded_size += PB._encoded_size(x.service_alert_id, 5))
    x.last_modified_time != zero(UInt64) && (encoded_size += PB._encoded_size(x.last_modified_time, 6))
    return encoded_size
end

struct TripDescriptor
    trip_id::String
    route_id::String
    direction_id::UInt32
    start_time::String
    start_date::String
    schedule_relationship::var"TripDescriptor.ScheduleRelationship".T
    modified_trip::Union{Nothing, var"TripDescriptor.ModifiedTripSelector"}
end
PB.extendable_field_numbers(::Type{TripDescriptor}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{TripDescriptor}) = (; trip_id = "", route_id = "", direction_id = zero(UInt32), start_time = "", start_date = "", schedule_relationship = var"TripDescriptor.ScheduleRelationship".SCHEDULED, modified_trip = nothing)
PB.field_numbers(::Type{TripDescriptor}) = (; trip_id = 1, route_id = 5, direction_id = 6, start_time = 2, start_date = 3, schedule_relationship = 4, modified_trip = 7)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TripDescriptor})
    trip_id = ""
    route_id = ""
    direction_id = zero(UInt32)
    start_time = ""
    start_date = ""
    schedule_relationship = var"TripDescriptor.ScheduleRelationship".SCHEDULED
    modified_trip = Ref{Union{Nothing, var"TripDescriptor.ModifiedTripSelector"}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            trip_id = PB.decode(d, String)
        elseif field_number == 5
            route_id = PB.decode(d, String)
        elseif field_number == 6
            direction_id = PB.decode(d, UInt32)
        elseif field_number == 2
            start_time = PB.decode(d, String)
        elseif field_number == 3
            start_date = PB.decode(d, String)
        elseif field_number == 4
            schedule_relationship = PB.decode(d, var"TripDescriptor.ScheduleRelationship".T)
        elseif field_number == 7
            PB.decode!(d, modified_trip)
        else
            Base.skip(d, wire_type)
        end
    end
    return TripDescriptor(trip_id, route_id, direction_id, start_time, start_date, schedule_relationship, modified_trip[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TripDescriptor)
    initpos = position(e.io)
    !isempty(x.trip_id) && PB.encode(e, 1, x.trip_id)
    !isempty(x.route_id) && PB.encode(e, 5, x.route_id)
    x.direction_id != zero(UInt32) && PB.encode(e, 6, x.direction_id)
    !isempty(x.start_time) && PB.encode(e, 2, x.start_time)
    !isempty(x.start_date) && PB.encode(e, 3, x.start_date)
    x.schedule_relationship != var"TripDescriptor.ScheduleRelationship".SCHEDULED && PB.encode(e, 4, x.schedule_relationship)
    !isnothing(x.modified_trip) && PB.encode(e, 7, x.modified_trip)
    return position(e.io) - initpos
end
function PB._encoded_size(x::TripDescriptor)
    encoded_size = 0
    !isempty(x.trip_id) && (encoded_size += PB._encoded_size(x.trip_id, 1))
    !isempty(x.route_id) && (encoded_size += PB._encoded_size(x.route_id, 5))
    x.direction_id != zero(UInt32) && (encoded_size += PB._encoded_size(x.direction_id, 6))
    !isempty(x.start_time) && (encoded_size += PB._encoded_size(x.start_time, 2))
    !isempty(x.start_date) && (encoded_size += PB._encoded_size(x.start_date, 3))
    x.schedule_relationship != var"TripDescriptor.ScheduleRelationship".SCHEDULED && (encoded_size += PB._encoded_size(x.schedule_relationship, 4))
    !isnothing(x.modified_trip) && (encoded_size += PB._encoded_size(x.modified_trip, 7))
    return encoded_size
end

struct Stop
    stop_id::String
    stop_code::Union{Nothing, TranslatedString}
    stop_name::Union{Nothing, TranslatedString}
    tts_stop_name::Union{Nothing, TranslatedString}
    stop_desc::Union{Nothing, TranslatedString}
    stop_lat::Float32
    stop_lon::Float32
    zone_id::String
    stop_url::Union{Nothing, TranslatedString}
    parent_station::String
    stop_timezone::String
    wheelchair_boarding::var"Stop.WheelchairBoarding".T
    level_id::String
    platform_code::Union{Nothing, TranslatedString}
end
PB.extendable_field_numbers(::Type{Stop}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{Stop}) = (; stop_id = "", stop_code = nothing, stop_name = nothing, tts_stop_name = nothing, stop_desc = nothing, stop_lat = zero(Float32), stop_lon = zero(Float32), zone_id = "", stop_url = nothing, parent_station = "", stop_timezone = "", wheelchair_boarding = var"Stop.WheelchairBoarding".UNKNOWN, level_id = "", platform_code = nothing)
PB.field_numbers(::Type{Stop}) = (; stop_id = 1, stop_code = 2, stop_name = 3, tts_stop_name = 4, stop_desc = 5, stop_lat = 6, stop_lon = 7, zone_id = 8, stop_url = 9, parent_station = 11, stop_timezone = 12, wheelchair_boarding = 13, level_id = 14, platform_code = 15)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Stop})
    stop_id = ""
    stop_code = Ref{Union{Nothing, TranslatedString}}(nothing)
    stop_name = Ref{Union{Nothing, TranslatedString}}(nothing)
    tts_stop_name = Ref{Union{Nothing, TranslatedString}}(nothing)
    stop_desc = Ref{Union{Nothing, TranslatedString}}(nothing)
    stop_lat = zero(Float32)
    stop_lon = zero(Float32)
    zone_id = ""
    stop_url = Ref{Union{Nothing, TranslatedString}}(nothing)
    parent_station = ""
    stop_timezone = ""
    wheelchair_boarding = var"Stop.WheelchairBoarding".UNKNOWN
    level_id = ""
    platform_code = Ref{Union{Nothing, TranslatedString}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            stop_id = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, stop_code)
        elseif field_number == 3
            PB.decode!(d, stop_name)
        elseif field_number == 4
            PB.decode!(d, tts_stop_name)
        elseif field_number == 5
            PB.decode!(d, stop_desc)
        elseif field_number == 6
            stop_lat = PB.decode(d, Float32)
        elseif field_number == 7
            stop_lon = PB.decode(d, Float32)
        elseif field_number == 8
            zone_id = PB.decode(d, String)
        elseif field_number == 9
            PB.decode!(d, stop_url)
        elseif field_number == 11
            parent_station = PB.decode(d, String)
        elseif field_number == 12
            stop_timezone = PB.decode(d, String)
        elseif field_number == 13
            wheelchair_boarding = PB.decode(d, var"Stop.WheelchairBoarding".T)
        elseif field_number == 14
            level_id = PB.decode(d, String)
        elseif field_number == 15
            PB.decode!(d, platform_code)
        else
            Base.skip(d, wire_type)
        end
    end
    return Stop(stop_id, stop_code[], stop_name[], tts_stop_name[], stop_desc[], stop_lat, stop_lon, zone_id, stop_url[], parent_station, stop_timezone, wheelchair_boarding, level_id, platform_code[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Stop)
    initpos = position(e.io)
    !isempty(x.stop_id) && PB.encode(e, 1, x.stop_id)
    !isnothing(x.stop_code) && PB.encode(e, 2, x.stop_code)
    !isnothing(x.stop_name) && PB.encode(e, 3, x.stop_name)
    !isnothing(x.tts_stop_name) && PB.encode(e, 4, x.tts_stop_name)
    !isnothing(x.stop_desc) && PB.encode(e, 5, x.stop_desc)
    x.stop_lat !== zero(Float32) && PB.encode(e, 6, x.stop_lat)
    x.stop_lon !== zero(Float32) && PB.encode(e, 7, x.stop_lon)
    !isempty(x.zone_id) && PB.encode(e, 8, x.zone_id)
    !isnothing(x.stop_url) && PB.encode(e, 9, x.stop_url)
    !isempty(x.parent_station) && PB.encode(e, 11, x.parent_station)
    !isempty(x.stop_timezone) && PB.encode(e, 12, x.stop_timezone)
    x.wheelchair_boarding != var"Stop.WheelchairBoarding".UNKNOWN && PB.encode(e, 13, x.wheelchair_boarding)
    !isempty(x.level_id) && PB.encode(e, 14, x.level_id)
    !isnothing(x.platform_code) && PB.encode(e, 15, x.platform_code)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Stop)
    encoded_size = 0
    !isempty(x.stop_id) && (encoded_size += PB._encoded_size(x.stop_id, 1))
    !isnothing(x.stop_code) && (encoded_size += PB._encoded_size(x.stop_code, 2))
    !isnothing(x.stop_name) && (encoded_size += PB._encoded_size(x.stop_name, 3))
    !isnothing(x.tts_stop_name) && (encoded_size += PB._encoded_size(x.tts_stop_name, 4))
    !isnothing(x.stop_desc) && (encoded_size += PB._encoded_size(x.stop_desc, 5))
    x.stop_lat !== zero(Float32) && (encoded_size += PB._encoded_size(x.stop_lat, 6))
    x.stop_lon !== zero(Float32) && (encoded_size += PB._encoded_size(x.stop_lon, 7))
    !isempty(x.zone_id) && (encoded_size += PB._encoded_size(x.zone_id, 8))
    !isnothing(x.stop_url) && (encoded_size += PB._encoded_size(x.stop_url, 9))
    !isempty(x.parent_station) && (encoded_size += PB._encoded_size(x.parent_station, 11))
    !isempty(x.stop_timezone) && (encoded_size += PB._encoded_size(x.stop_timezone, 12))
    x.wheelchair_boarding != var"Stop.WheelchairBoarding".UNKNOWN && (encoded_size += PB._encoded_size(x.wheelchair_boarding, 13))
    !isempty(x.level_id) && (encoded_size += PB._encoded_size(x.level_id, 14))
    !isnothing(x.platform_code) && (encoded_size += PB._encoded_size(x.platform_code, 15))
    return encoded_size
end

struct var"TripUpdate.StopTimeUpdate"
    stop_sequence::UInt32
    stop_id::String
    arrival::Union{Nothing, var"TripUpdate.StopTimeEvent"}
    departure::Union{Nothing, var"TripUpdate.StopTimeEvent"}
    departure_occupancy_status::var"VehiclePosition.OccupancyStatus".T
    schedule_relationship::var"TripUpdate.StopTimeUpdate.ScheduleRelationship".T
    stop_time_properties::Union{Nothing, var"TripUpdate.StopTimeUpdate.StopTimeProperties"}
end
PB.extendable_field_numbers(::Type{var"TripUpdate.StopTimeUpdate"}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{var"TripUpdate.StopTimeUpdate"}) = (; stop_sequence = zero(UInt32), stop_id = "", arrival = nothing, departure = nothing, departure_occupancy_status = var"VehiclePosition.OccupancyStatus".EMPTY, schedule_relationship = var"TripUpdate.StopTimeUpdate.ScheduleRelationship".SCHEDULED, stop_time_properties = nothing)
PB.field_numbers(::Type{var"TripUpdate.StopTimeUpdate"}) = (; stop_sequence = 1, stop_id = 4, arrival = 2, departure = 3, departure_occupancy_status = 7, schedule_relationship = 5, stop_time_properties = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"TripUpdate.StopTimeUpdate"})
    stop_sequence = zero(UInt32)
    stop_id = ""
    arrival = Ref{Union{Nothing, var"TripUpdate.StopTimeEvent"}}(nothing)
    departure = Ref{Union{Nothing, var"TripUpdate.StopTimeEvent"}}(nothing)
    departure_occupancy_status = var"VehiclePosition.OccupancyStatus".EMPTY
    schedule_relationship = var"TripUpdate.StopTimeUpdate.ScheduleRelationship".SCHEDULED
    stop_time_properties = Ref{Union{Nothing, var"TripUpdate.StopTimeUpdate.StopTimeProperties"}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            stop_sequence = PB.decode(d, UInt32)
        elseif field_number == 4
            stop_id = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, arrival)
        elseif field_number == 3
            PB.decode!(d, departure)
        elseif field_number == 7
            departure_occupancy_status = PB.decode(d, var"VehiclePosition.OccupancyStatus".T)
        elseif field_number == 5
            schedule_relationship = PB.decode(d, var"TripUpdate.StopTimeUpdate.ScheduleRelationship".T)
        elseif field_number == 6
            PB.decode!(d, stop_time_properties)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"TripUpdate.StopTimeUpdate"(stop_sequence, stop_id, arrival[], departure[], departure_occupancy_status, schedule_relationship, stop_time_properties[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"TripUpdate.StopTimeUpdate")
    initpos = position(e.io)
    x.stop_sequence != zero(UInt32) && PB.encode(e, 1, x.stop_sequence)
    !isempty(x.stop_id) && PB.encode(e, 4, x.stop_id)
    !isnothing(x.arrival) && PB.encode(e, 2, x.arrival)
    !isnothing(x.departure) && PB.encode(e, 3, x.departure)
    x.departure_occupancy_status != var"VehiclePosition.OccupancyStatus".EMPTY && PB.encode(e, 7, x.departure_occupancy_status)
    x.schedule_relationship != var"TripUpdate.StopTimeUpdate.ScheduleRelationship".SCHEDULED && PB.encode(e, 5, x.schedule_relationship)
    !isnothing(x.stop_time_properties) && PB.encode(e, 6, x.stop_time_properties)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"TripUpdate.StopTimeUpdate")
    encoded_size = 0
    x.stop_sequence != zero(UInt32) && (encoded_size += PB._encoded_size(x.stop_sequence, 1))
    !isempty(x.stop_id) && (encoded_size += PB._encoded_size(x.stop_id, 4))
    !isnothing(x.arrival) && (encoded_size += PB._encoded_size(x.arrival, 2))
    !isnothing(x.departure) && (encoded_size += PB._encoded_size(x.departure, 3))
    x.departure_occupancy_status != var"VehiclePosition.OccupancyStatus".EMPTY && (encoded_size += PB._encoded_size(x.departure_occupancy_status, 7))
    x.schedule_relationship != var"TripUpdate.StopTimeUpdate.ScheduleRelationship".SCHEDULED && (encoded_size += PB._encoded_size(x.schedule_relationship, 5))
    !isnothing(x.stop_time_properties) && (encoded_size += PB._encoded_size(x.stop_time_properties, 6))
    return encoded_size
end

struct TripModifications
    selected_trips::Vector{var"TripModifications.SelectedTrips"}
    start_times::Vector{String}
    service_dates::Vector{String}
    modifications::Vector{var"TripModifications.Modification"}
end
PB.extendable_field_numbers(::Type{TripModifications}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{TripModifications}) = (; selected_trips = Vector{var"TripModifications.SelectedTrips"}(), start_times = Vector{String}(), service_dates = Vector{String}(), modifications = Vector{var"TripModifications.Modification"}())
PB.field_numbers(::Type{TripModifications}) = (; selected_trips = 1, start_times = 2, service_dates = 3, modifications = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TripModifications})
    selected_trips = PB.BufferedVector{var"TripModifications.SelectedTrips"}()
    start_times = PB.BufferedVector{String}()
    service_dates = PB.BufferedVector{String}()
    modifications = PB.BufferedVector{var"TripModifications.Modification"}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, selected_trips)
        elseif field_number == 2
            PB.decode!(d, start_times)
        elseif field_number == 3
            PB.decode!(d, service_dates)
        elseif field_number == 4
            PB.decode!(d, modifications)
        else
            Base.skip(d, wire_type)
        end
    end
    return TripModifications(selected_trips[], start_times[], service_dates[], modifications[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TripModifications)
    initpos = position(e.io)
    !isempty(x.selected_trips) && PB.encode(e, 1, x.selected_trips)
    !isempty(x.start_times) && PB.encode(e, 2, x.start_times)
    !isempty(x.service_dates) && PB.encode(e, 3, x.service_dates)
    !isempty(x.modifications) && PB.encode(e, 4, x.modifications)
    return position(e.io) - initpos
end
function PB._encoded_size(x::TripModifications)
    encoded_size = 0
    !isempty(x.selected_trips) && (encoded_size += PB._encoded_size(x.selected_trips, 1))
    !isempty(x.start_times) && (encoded_size += PB._encoded_size(x.start_times, 2))
    !isempty(x.service_dates) && (encoded_size += PB._encoded_size(x.service_dates, 3))
    !isempty(x.modifications) && (encoded_size += PB._encoded_size(x.modifications, 4))
    return encoded_size
end

struct EntitySelector
    agency_id::String
    route_id::String
    route_type::Int32
    trip::Union{Nothing, TripDescriptor}
    stop_id::String
    direction_id::UInt32
end
PB.extendable_field_numbers(::Type{EntitySelector}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{EntitySelector}) = (; agency_id = "", route_id = "", route_type = zero(Int32), trip = nothing, stop_id = "", direction_id = zero(UInt32))
PB.field_numbers(::Type{EntitySelector}) = (; agency_id = 1, route_id = 2, route_type = 3, trip = 4, stop_id = 5, direction_id = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:EntitySelector})
    agency_id = ""
    route_id = ""
    route_type = zero(Int32)
    trip = Ref{Union{Nothing, TripDescriptor}}(nothing)
    stop_id = ""
    direction_id = zero(UInt32)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            agency_id = PB.decode(d, String)
        elseif field_number == 2
            route_id = PB.decode(d, String)
        elseif field_number == 3
            route_type = PB.decode(d, Int32)
        elseif field_number == 4
            PB.decode!(d, trip)
        elseif field_number == 5
            stop_id = PB.decode(d, String)
        elseif field_number == 6
            direction_id = PB.decode(d, UInt32)
        else
            Base.skip(d, wire_type)
        end
    end
    return EntitySelector(agency_id, route_id, route_type, trip[], stop_id, direction_id)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::EntitySelector)
    initpos = position(e.io)
    !isempty(x.agency_id) && PB.encode(e, 1, x.agency_id)
    !isempty(x.route_id) && PB.encode(e, 2, x.route_id)
    x.route_type != zero(Int32) && PB.encode(e, 3, x.route_type)
    !isnothing(x.trip) && PB.encode(e, 4, x.trip)
    !isempty(x.stop_id) && PB.encode(e, 5, x.stop_id)
    x.direction_id != zero(UInt32) && PB.encode(e, 6, x.direction_id)
    return position(e.io) - initpos
end
function PB._encoded_size(x::EntitySelector)
    encoded_size = 0
    !isempty(x.agency_id) && (encoded_size += PB._encoded_size(x.agency_id, 1))
    !isempty(x.route_id) && (encoded_size += PB._encoded_size(x.route_id, 2))
    x.route_type != zero(Int32) && (encoded_size += PB._encoded_size(x.route_type, 3))
    !isnothing(x.trip) && (encoded_size += PB._encoded_size(x.trip, 4))
    !isempty(x.stop_id) && (encoded_size += PB._encoded_size(x.stop_id, 5))
    x.direction_id != zero(UInt32) && (encoded_size += PB._encoded_size(x.direction_id, 6))
    return encoded_size
end

struct VehiclePosition
    trip::Union{Nothing, TripDescriptor}
    vehicle::Union{Nothing, VehicleDescriptor}
    position::Union{Nothing, Position}
    current_stop_sequence::UInt32
    stop_id::String
    current_status::var"VehiclePosition.VehicleStopStatus".T
    timestamp::UInt64
    congestion_level::var"VehiclePosition.CongestionLevel".T
    occupancy_status::var"VehiclePosition.OccupancyStatus".T
    occupancy_percentage::UInt32
    multi_carriage_details::Vector{var"VehiclePosition.CarriageDetails"}
end
PB.extendable_field_numbers(::Type{VehiclePosition}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{VehiclePosition}) = (; trip = nothing, vehicle = nothing, position = nothing, current_stop_sequence = zero(UInt32), stop_id = "", current_status = var"VehiclePosition.VehicleStopStatus".IN_TRANSIT_TO, timestamp = zero(UInt64), congestion_level = var"VehiclePosition.CongestionLevel".UNKNOWN_CONGESTION_LEVEL, occupancy_status = var"VehiclePosition.OccupancyStatus".EMPTY, occupancy_percentage = zero(UInt32), multi_carriage_details = Vector{var"VehiclePosition.CarriageDetails"}())
PB.field_numbers(::Type{VehiclePosition}) = (; trip = 1, vehicle = 8, position = 2, current_stop_sequence = 3, stop_id = 7, current_status = 4, timestamp = 5, congestion_level = 6, occupancy_status = 9, occupancy_percentage = 10, multi_carriage_details = 11)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:VehiclePosition})
    trip = Ref{Union{Nothing, TripDescriptor}}(nothing)
    vehicle = Ref{Union{Nothing, VehicleDescriptor}}(nothing)
    position = Ref{Union{Nothing, Position}}(nothing)
    current_stop_sequence = zero(UInt32)
    stop_id = ""
    current_status = var"VehiclePosition.VehicleStopStatus".IN_TRANSIT_TO
    timestamp = zero(UInt64)
    congestion_level = var"VehiclePosition.CongestionLevel".UNKNOWN_CONGESTION_LEVEL
    occupancy_status = var"VehiclePosition.OccupancyStatus".EMPTY
    occupancy_percentage = zero(UInt32)
    multi_carriage_details = PB.BufferedVector{var"VehiclePosition.CarriageDetails"}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, trip)
        elseif field_number == 8
            PB.decode!(d, vehicle)
        elseif field_number == 2
            PB.decode!(d, position)
        elseif field_number == 3
            current_stop_sequence = PB.decode(d, UInt32)
        elseif field_number == 7
            stop_id = PB.decode(d, String)
        elseif field_number == 4
            current_status = PB.decode(d, var"VehiclePosition.VehicleStopStatus".T)
        elseif field_number == 5
            timestamp = PB.decode(d, UInt64)
        elseif field_number == 6
            congestion_level = PB.decode(d, var"VehiclePosition.CongestionLevel".T)
        elseif field_number == 9
            occupancy_status = PB.decode(d, var"VehiclePosition.OccupancyStatus".T)
        elseif field_number == 10
            occupancy_percentage = PB.decode(d, UInt32)
        elseif field_number == 11
            PB.decode!(d, multi_carriage_details)
        else
            Base.skip(d, wire_type)
        end
    end
    return VehiclePosition(trip[], vehicle[], position[], current_stop_sequence, stop_id, current_status, timestamp, congestion_level, occupancy_status, occupancy_percentage, multi_carriage_details[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::VehiclePosition)
    initpos = position(e.io)
    !isnothing(x.trip) && PB.encode(e, 1, x.trip)
    !isnothing(x.vehicle) && PB.encode(e, 8, x.vehicle)
    !isnothing(x.position) && PB.encode(e, 2, x.position)
    x.current_stop_sequence != zero(UInt32) && PB.encode(e, 3, x.current_stop_sequence)
    !isempty(x.stop_id) && PB.encode(e, 7, x.stop_id)
    x.current_status != var"VehiclePosition.VehicleStopStatus".IN_TRANSIT_TO && PB.encode(e, 4, x.current_status)
    x.timestamp != zero(UInt64) && PB.encode(e, 5, x.timestamp)
    x.congestion_level != var"VehiclePosition.CongestionLevel".UNKNOWN_CONGESTION_LEVEL && PB.encode(e, 6, x.congestion_level)
    x.occupancy_status != var"VehiclePosition.OccupancyStatus".EMPTY && PB.encode(e, 9, x.occupancy_status)
    x.occupancy_percentage != zero(UInt32) && PB.encode(e, 10, x.occupancy_percentage)
    !isempty(x.multi_carriage_details) && PB.encode(e, 11, x.multi_carriage_details)
    return position(e.io) - initpos
end
function PB._encoded_size(x::VehiclePosition)
    encoded_size = 0
    !isnothing(x.trip) && (encoded_size += PB._encoded_size(x.trip, 1))
    !isnothing(x.vehicle) && (encoded_size += PB._encoded_size(x.vehicle, 8))
    !isnothing(x.position) && (encoded_size += PB._encoded_size(x.position, 2))
    x.current_stop_sequence != zero(UInt32) && (encoded_size += PB._encoded_size(x.current_stop_sequence, 3))
    !isempty(x.stop_id) && (encoded_size += PB._encoded_size(x.stop_id, 7))
    x.current_status != var"VehiclePosition.VehicleStopStatus".IN_TRANSIT_TO && (encoded_size += PB._encoded_size(x.current_status, 4))
    x.timestamp != zero(UInt64) && (encoded_size += PB._encoded_size(x.timestamp, 5))
    x.congestion_level != var"VehiclePosition.CongestionLevel".UNKNOWN_CONGESTION_LEVEL && (encoded_size += PB._encoded_size(x.congestion_level, 6))
    x.occupancy_status != var"VehiclePosition.OccupancyStatus".EMPTY && (encoded_size += PB._encoded_size(x.occupancy_status, 9))
    x.occupancy_percentage != zero(UInt32) && (encoded_size += PB._encoded_size(x.occupancy_percentage, 10))
    !isempty(x.multi_carriage_details) && (encoded_size += PB._encoded_size(x.multi_carriage_details, 11))
    return encoded_size
end

struct TripUpdate
    trip::TripDescriptor
    vehicle::Union{Nothing, VehicleDescriptor}
    stop_time_update::Vector{var"TripUpdate.StopTimeUpdate"}
    timestamp::UInt64
    delay::Int32
    trip_properties::Union{Nothing, var"TripUpdate.TripProperties"}
end
PB.extendable_field_numbers(::Type{TripUpdate}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{TripUpdate}) = (; trip, vehicle = nothing, stop_time_update = Vector{var"TripUpdate.StopTimeUpdate"}(), timestamp = zero(UInt64), delay = zero(Int32), trip_properties = nothing)
PB.field_numbers(::Type{TripUpdate}) = (; trip = 1, vehicle = 3, stop_time_update = 2, timestamp = 4, delay = 5, trip_properties = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TripUpdate})
    trip = Ref{TripDescriptor}()
    vehicle = Ref{Union{Nothing, VehicleDescriptor}}(nothing)
    stop_time_update = PB.BufferedVector{var"TripUpdate.StopTimeUpdate"}()
    timestamp = zero(UInt64)
    delay = zero(Int32)
    trip_properties = Ref{Union{Nothing, var"TripUpdate.TripProperties"}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, trip)
        elseif field_number == 3
            PB.decode!(d, vehicle)
        elseif field_number == 2
            PB.decode!(d, stop_time_update)
        elseif field_number == 4
            timestamp = PB.decode(d, UInt64)
        elseif field_number == 5
            delay = PB.decode(d, Int32)
        elseif field_number == 6
            PB.decode!(d, trip_properties)
        else
            Base.skip(d, wire_type)
        end
    end
    return TripUpdate(trip[], vehicle[], stop_time_update[], timestamp, delay, trip_properties[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TripUpdate)
    initpos = position(e.io)
    PB.encode(e, 1, x.trip)
    !isnothing(x.vehicle) && PB.encode(e, 3, x.vehicle)
    !isempty(x.stop_time_update) && PB.encode(e, 2, x.stop_time_update)
    x.timestamp != zero(UInt64) && PB.encode(e, 4, x.timestamp)
    x.delay != zero(Int32) && PB.encode(e, 5, x.delay)
    !isnothing(x.trip_properties) && PB.encode(e, 6, x.trip_properties)
    return position(e.io) - initpos
end
function PB._encoded_size(x::TripUpdate)
    encoded_size = 0
    encoded_size += PB._encoded_size(x.trip, 1)
    !isnothing(x.vehicle) && (encoded_size += PB._encoded_size(x.vehicle, 3))
    !isempty(x.stop_time_update) && (encoded_size += PB._encoded_size(x.stop_time_update, 2))
    x.timestamp != zero(UInt64) && (encoded_size += PB._encoded_size(x.timestamp, 4))
    x.delay != zero(Int32) && (encoded_size += PB._encoded_size(x.delay, 5))
    !isnothing(x.trip_properties) && (encoded_size += PB._encoded_size(x.trip_properties, 6))
    return encoded_size
end

struct Alert
    active_period::Vector{TimeRange}
    informed_entity::Vector{EntitySelector}
    cause::var"Alert.Cause".T
    effect::var"Alert.Effect".T
    url::Union{Nothing, TranslatedString}
    header_text::Union{Nothing, TranslatedString}
    description_text::Union{Nothing, TranslatedString}
    tts_header_text::Union{Nothing, TranslatedString}
    tts_description_text::Union{Nothing, TranslatedString}
    severity_level::var"Alert.SeverityLevel".T
    image::Union{Nothing, TranslatedImage}
    image_alternative_text::Union{Nothing, TranslatedString}
    cause_detail::Union{Nothing, TranslatedString}
    effect_detail::Union{Nothing, TranslatedString}
end
PB.extendable_field_numbers(::Type{Alert}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{Alert}) = (; active_period = Vector{TimeRange}(), informed_entity = Vector{EntitySelector}(), cause = var"Alert.Cause".UNKNOWN_CAUSE, effect = var"Alert.Effect".UNKNOWN_EFFECT, url = nothing, header_text = nothing, description_text = nothing, tts_header_text = nothing, tts_description_text = nothing, severity_level = var"Alert.SeverityLevel".UNKNOWN_SEVERITY, image = nothing, image_alternative_text = nothing, cause_detail = nothing, effect_detail = nothing)
PB.field_numbers(::Type{Alert}) = (; active_period = 1, informed_entity = 5, cause = 6, effect = 7, url = 8, header_text = 10, description_text = 11, tts_header_text = 12, tts_description_text = 13, severity_level = 14, image = 15, image_alternative_text = 16, cause_detail = 17, effect_detail = 18)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Alert})
    active_period = PB.BufferedVector{TimeRange}()
    informed_entity = PB.BufferedVector{EntitySelector}()
    cause = var"Alert.Cause".UNKNOWN_CAUSE
    effect = var"Alert.Effect".UNKNOWN_EFFECT
    url = Ref{Union{Nothing, TranslatedString}}(nothing)
    header_text = Ref{Union{Nothing, TranslatedString}}(nothing)
    description_text = Ref{Union{Nothing, TranslatedString}}(nothing)
    tts_header_text = Ref{Union{Nothing, TranslatedString}}(nothing)
    tts_description_text = Ref{Union{Nothing, TranslatedString}}(nothing)
    severity_level = var"Alert.SeverityLevel".UNKNOWN_SEVERITY
    image = Ref{Union{Nothing, TranslatedImage}}(nothing)
    image_alternative_text = Ref{Union{Nothing, TranslatedString}}(nothing)
    cause_detail = Ref{Union{Nothing, TranslatedString}}(nothing)
    effect_detail = Ref{Union{Nothing, TranslatedString}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, active_period)
        elseif field_number == 5
            PB.decode!(d, informed_entity)
        elseif field_number == 6
            cause = PB.decode(d, var"Alert.Cause".T)
        elseif field_number == 7
            effect = PB.decode(d, var"Alert.Effect".T)
        elseif field_number == 8
            PB.decode!(d, url)
        elseif field_number == 10
            PB.decode!(d, header_text)
        elseif field_number == 11
            PB.decode!(d, description_text)
        elseif field_number == 12
            PB.decode!(d, tts_header_text)
        elseif field_number == 13
            PB.decode!(d, tts_description_text)
        elseif field_number == 14
            severity_level = PB.decode(d, var"Alert.SeverityLevel".T)
        elseif field_number == 15
            PB.decode!(d, image)
        elseif field_number == 16
            PB.decode!(d, image_alternative_text)
        elseif field_number == 17
            PB.decode!(d, cause_detail)
        elseif field_number == 18
            PB.decode!(d, effect_detail)
        else
            Base.skip(d, wire_type)
        end
    end
    return Alert(active_period[], informed_entity[], cause, effect, url[], header_text[], description_text[], tts_header_text[], tts_description_text[], severity_level, image[], image_alternative_text[], cause_detail[], effect_detail[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Alert)
    initpos = position(e.io)
    !isempty(x.active_period) && PB.encode(e, 1, x.active_period)
    !isempty(x.informed_entity) && PB.encode(e, 5, x.informed_entity)
    x.cause != var"Alert.Cause".UNKNOWN_CAUSE && PB.encode(e, 6, x.cause)
    x.effect != var"Alert.Effect".UNKNOWN_EFFECT && PB.encode(e, 7, x.effect)
    !isnothing(x.url) && PB.encode(e, 8, x.url)
    !isnothing(x.header_text) && PB.encode(e, 10, x.header_text)
    !isnothing(x.description_text) && PB.encode(e, 11, x.description_text)
    !isnothing(x.tts_header_text) && PB.encode(e, 12, x.tts_header_text)
    !isnothing(x.tts_description_text) && PB.encode(e, 13, x.tts_description_text)
    x.severity_level != var"Alert.SeverityLevel".UNKNOWN_SEVERITY && PB.encode(e, 14, x.severity_level)
    !isnothing(x.image) && PB.encode(e, 15, x.image)
    !isnothing(x.image_alternative_text) && PB.encode(e, 16, x.image_alternative_text)
    !isnothing(x.cause_detail) && PB.encode(e, 17, x.cause_detail)
    !isnothing(x.effect_detail) && PB.encode(e, 18, x.effect_detail)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Alert)
    encoded_size = 0
    !isempty(x.active_period) && (encoded_size += PB._encoded_size(x.active_period, 1))
    !isempty(x.informed_entity) && (encoded_size += PB._encoded_size(x.informed_entity, 5))
    x.cause != var"Alert.Cause".UNKNOWN_CAUSE && (encoded_size += PB._encoded_size(x.cause, 6))
    x.effect != var"Alert.Effect".UNKNOWN_EFFECT && (encoded_size += PB._encoded_size(x.effect, 7))
    !isnothing(x.url) && (encoded_size += PB._encoded_size(x.url, 8))
    !isnothing(x.header_text) && (encoded_size += PB._encoded_size(x.header_text, 10))
    !isnothing(x.description_text) && (encoded_size += PB._encoded_size(x.description_text, 11))
    !isnothing(x.tts_header_text) && (encoded_size += PB._encoded_size(x.tts_header_text, 12))
    !isnothing(x.tts_description_text) && (encoded_size += PB._encoded_size(x.tts_description_text, 13))
    x.severity_level != var"Alert.SeverityLevel".UNKNOWN_SEVERITY && (encoded_size += PB._encoded_size(x.severity_level, 14))
    !isnothing(x.image) && (encoded_size += PB._encoded_size(x.image, 15))
    !isnothing(x.image_alternative_text) && (encoded_size += PB._encoded_size(x.image_alternative_text, 16))
    !isnothing(x.cause_detail) && (encoded_size += PB._encoded_size(x.cause_detail, 17))
    !isnothing(x.effect_detail) && (encoded_size += PB._encoded_size(x.effect_detail, 18))
    return encoded_size
end

struct FeedEntity
    id::String
    is_deleted::Bool
    trip_update::Union{Nothing, TripUpdate}
    vehicle::Union{Nothing, VehiclePosition}
    alert::Union{Nothing, Alert}
    shape::Union{Nothing, Shape}
    stop::Union{Nothing, Stop}
    trip_modifications::Union{Nothing, TripModifications}
end
PB.extendable_field_numbers(::Type{FeedEntity}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{FeedEntity}) = (; id = "", is_deleted = false, trip_update = nothing, vehicle = nothing, alert = nothing, shape = nothing, stop = nothing, trip_modifications = nothing)
PB.field_numbers(::Type{FeedEntity}) = (; id = 1, is_deleted = 2, trip_update = 3, vehicle = 4, alert = 5, shape = 6, stop = 7, trip_modifications = 8)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:FeedEntity})
    id = ""
    is_deleted = false
    trip_update = Ref{Union{Nothing, TripUpdate}}(nothing)
    vehicle = Ref{Union{Nothing, VehiclePosition}}(nothing)
    alert = Ref{Union{Nothing, Alert}}(nothing)
    shape = Ref{Union{Nothing, Shape}}(nothing)
    stop = Ref{Union{Nothing, Stop}}(nothing)
    trip_modifications = Ref{Union{Nothing, TripModifications}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            id = PB.decode(d, String)
        elseif field_number == 2
            is_deleted = PB.decode(d, Bool)
        elseif field_number == 3
            PB.decode!(d, trip_update)
        elseif field_number == 4
            PB.decode!(d, vehicle)
        elseif field_number == 5
            PB.decode!(d, alert)
        elseif field_number == 6
            PB.decode!(d, shape)
        elseif field_number == 7
            PB.decode!(d, stop)
        elseif field_number == 8
            PB.decode!(d, trip_modifications)
        else
            Base.skip(d, wire_type)
        end
    end
    return FeedEntity(id, is_deleted, trip_update[], vehicle[], alert[], shape[], stop[], trip_modifications[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::FeedEntity)
    initpos = position(e.io)
    PB.encode(e, 1, x.id)
    x.is_deleted != false && PB.encode(e, 2, x.is_deleted)
    !isnothing(x.trip_update) && PB.encode(e, 3, x.trip_update)
    !isnothing(x.vehicle) && PB.encode(e, 4, x.vehicle)
    !isnothing(x.alert) && PB.encode(e, 5, x.alert)
    !isnothing(x.shape) && PB.encode(e, 6, x.shape)
    !isnothing(x.stop) && PB.encode(e, 7, x.stop)
    !isnothing(x.trip_modifications) && PB.encode(e, 8, x.trip_modifications)
    return position(e.io) - initpos
end
function PB._encoded_size(x::FeedEntity)
    encoded_size = 0
    encoded_size += PB._encoded_size(x.id, 1)
    x.is_deleted != false && (encoded_size += PB._encoded_size(x.is_deleted, 2))
    !isnothing(x.trip_update) && (encoded_size += PB._encoded_size(x.trip_update, 3))
    !isnothing(x.vehicle) && (encoded_size += PB._encoded_size(x.vehicle, 4))
    !isnothing(x.alert) && (encoded_size += PB._encoded_size(x.alert, 5))
    !isnothing(x.shape) && (encoded_size += PB._encoded_size(x.shape, 6))
    !isnothing(x.stop) && (encoded_size += PB._encoded_size(x.stop, 7))
    !isnothing(x.trip_modifications) && (encoded_size += PB._encoded_size(x.trip_modifications, 8))
    return encoded_size
end

struct FeedMessage
    header::FeedHeader
    entity::Vector{FeedEntity}
end
PB.extendable_field_numbers(::Type{FeedMessage}) = Union{Int, UnitRange{Int}}[1000:1999, 9000:9999]
PB.default_values(::Type{FeedMessage}) = (; header, entity = Vector{FeedEntity}())
PB.field_numbers(::Type{FeedMessage}) = (; header = 1, entity = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:FeedMessage})
    header = Ref{FeedHeader}()
    entity = PB.BufferedVector{FeedEntity}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, header)
        elseif field_number == 2
            PB.decode!(d, entity)
        else
            Base.skip(d, wire_type)
        end
    end
    return FeedMessage(header[], entity[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::FeedMessage)
    initpos = position(e.io)
    PB.encode(e, 1, x.header)
    !isempty(x.entity) && PB.encode(e, 2, x.entity)
    return position(e.io) - initpos
end
function PB._encoded_size(x::FeedMessage)
    encoded_size = 0
    encoded_size += PB._encoded_size(x.header, 1)
    !isempty(x.entity) && (encoded_size += PB._encoded_size(x.entity, 2))
    return encoded_size
end
